version: "3"

services:
  mysql-db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
    ports:
      - "13306:3306"

  clickhouse-db:
    image: clickhouse/clickhouse-server:latest
    environment: 
      CLICKHOUSE_USER: default 
      CLICKHOUSE_PASSWORD: qwerty123 
    ports:
      - "18123:8123"
      - "19000:9000"

  prometheus:
    image: prom/prometheus:latest
    volumes: 
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - "19090:9090"

  grafana:
    image: grafana/grafana-oss:9.4.3
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "13000:3000"

volumes:
  grafana-data:
